# Generated by Django 5.2.7 on 2025-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('required', models.TextField(max_length=1000)),
                ('experience', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('application_date', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=15)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=15)),
            ],
        ),
    ]
