# Generated by Django 5.2.7 on 2025-11-18 17:45

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.ImageField(default=None, upload_to=Job.models.image_upload),
        ),
    ]
