# Generated by Django 5.2.7 on 2025-11-18 18:33

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_job_job_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.ImageField(upload_to=Job.models.image_upload),
        ),
    ]
